import 'dart:convert';
import 'package:http/http.dart' as http;

class OpenRouterAIService {
  static const String _baseUrl = 'https://openrouter.ai/api/v1';
  static const String _apiKey = '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';
  
  static Future<String> generateBusinessPlan({
    required String businessName,
    required String businessType,
    required String industry,
    required String targetMarket,
    required String businessModel,
    required String fundingGoal,
    required String timeline,
    required String description,
  }) async {
    try {
      final prompt = '''
Create a comprehensive business plan for the following business:

Business Name: $businessName
Business Type: $businessType
Industry: $industry
Target Market: $targetMarket
Business Model: $businessModel
Funding Goal: \$$fundingGoal
Timeline: $timeline
Description: $description

Please provide a detailed business plan that includes:
1. Executive Summary
2. Company Description
3. Market Analysis
4. Organization & Management
5. Products/Services
6. Marketing & Sales Strategy
7. Financial Projections
8. Funding Requirements
9. Risk Analysis
10. Implementation Timeline

Format the response in a clear, professional manner with proper headings and detailed content for each section.
''';

      print('🚀 Starting OpenRouter API call...');
      print('   URL: $_baseUrl/chat/completions');
      print('   Model: openai/gpt-3.5-turbo');
      print('   Prompt length: ${prompt.length} characters');

      final requestBody = {
        'model': 'openai/gpt-3.5-turbo',
        'messages': [
          {
            'role': 'system',
            'content': 'You are a professional business consultant with expertise in creating comprehensive business plans. Provide detailed, actionable, and realistic business plans.'
          },
          {
            'role': 'user',
            'content': prompt,
          }
        ],
        'temperature': 0.7,
        'max_tokens': 4000,
      };

      print('   Request body prepared, making HTTP POST request...');

      final response = await http.post(
        Uri.parse('$_baseUrl/chat/completions'),
        headers: {
          'Authorization': 'Bearer $_apiKey',
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://biznest.app',
          'X-Title': 'BizNest Business Plan Generator',
        },
        body: jsonEncode(requestBody),
      ).timeout(
        const Duration(seconds: 60), // 60 second timeout
        onTimeout: () {
          print('❌ Request timed out after 60 seconds');
          throw Exception('Request timed out. Please check your internet connection and try again.');
        },
      );

      print('✅ Received response from OpenRouter API');
      print('   Status Code: ${response.statusCode}');
      print('   Response Length: ${response.body.length} characters');
      print('   Response Headers: ${response.headers}');

      if (response.statusCode == 200) {
        print('🔍 Parsing JSON response...');
        final data = jsonDecode(response.body);
        
        print('   Response structure: ${data.keys.toList()}');
        
        if (data['choices'] == null || data['choices'].isEmpty) {
          print('❌ No choices in response');
          throw Exception('No response generated by AI. Please try again.');
        }
        
        print('   Found ${data['choices'].length} choice(s)');
        final content = data['choices'][0]['message']['content'];
        
        if (content == null || content.toString().trim().isEmpty) {
          print('❌ Content is null or empty');
          throw Exception('Empty response from AI. Please try again.');
        }
        
        print('✅ Successfully generated content');
        print('   Content length: ${content.toString().length} characters');
        print('   First 200 chars: ${content.toString().length > 200 ? "${content.toString().substring(0, 200)}..." : content.toString()}');
        return content.toString();
      } else {
        print('❌ API returned error status: ${response.statusCode}');
        print('   Error response body: ${response.body}');
        throw Exception('Failed to generate business plan: HTTP ${response.statusCode}. ${response.body}');
      }
    } catch (e) {
      print('Error in generateBusinessPlan: $e');
      if (e.toString().contains('timeout') || e.toString().contains('Timeout')) {
        throw Exception('Request timed out. Please check your internet connection and try again.');
      } else if (e.toString().contains('SocketException')) {
        throw Exception('Network error. Please check your internet connection.');
      } else {
        throw Exception('Error generating business plan: $e');
      }
    }
  }

  static Future<String> generateMarketAnalysis({
    required String industry,
    required String targetMarket,
    required String location,
  }) async {
    try {
      final prompt = '''
Provide a comprehensive market analysis for:

Industry: $industry
Target Market: $targetMarket
Location: $location

Include:
1. Market Size and Growth Trends
2. Target Customer Demographics
3. Competitive Landscape
4. Market Opportunities
5. Potential Challenges
6. Key Success Factors
7. Pricing Strategy Recommendations
8. Market Entry Strategy

Provide specific data, statistics, and actionable insights.
''';

      final response = await http.post(
        Uri.parse('$_baseUrl/chat/completions'),
        headers: {
          'Authorization': 'Bearer $_apiKey',
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://biznest.app',
          'X-Title': 'BizNest Market Research Tool',
        },
        body: jsonEncode({
          'model': 'openai/gpt-3.5-turbo',
          'messages': [
            {
              'role': 'system',
              'content': 'You are a market research expert. Provide detailed market analysis with specific insights and data.'
            },
            {
              'role': 'user',
              'content': prompt,
            }
          ],
          'temperature': 0.5,
          'max_tokens': 3000,
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['choices'][0]['message']['content'];
      } else {
        throw Exception('Failed to generate market analysis: ${response.statusCode}');
      }
    } catch (e) {
      throw Exception('Error generating market analysis: $e');
    }
  }

  static Future<Map<String, String>> generateSWOTAnalysis({
    required String businessName,
    required String industry,
    required String businessModel,
  }) async {
    try {
      final prompt = '''
Create a detailed SWOT analysis for:

Business: $businessName
Industry: $industry
Business Model: $businessModel

Provide specific points for each category:
- Strengths (internal positive factors)
- Weaknesses (internal areas for improvement)
- Opportunities (external positive factors)
- Threats (external challenges)

Format as JSON with keys: strengths, weaknesses, opportunities, threats
Each should be an array of specific, actionable points.
''';

      final response = await http.post(
        Uri.parse('$_baseUrl/chat/completions'),
        headers: {
          'Authorization': 'Bearer $_apiKey',
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://biznest.app',
          'X-Title': 'BizNest SWOT Analysis Tool',
        },
        body: jsonEncode({
          'model': 'openai/gpt-3.5-turbo',
          'messages': [
            {
              'role': 'system',
              'content': 'You are a business strategy consultant. Create specific, actionable SWOT analyses.'
            },
            {
              'role': 'user',
              'content': prompt,
            }
          ],
          'temperature': 0.6,
          'max_tokens': 2000,
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final content = data['choices'][0]['message']['content'];
        
        // Try to parse as JSON, fallback to text format
        try {
          final swotData = jsonDecode(content);
          return {
            'strengths': (swotData['strengths'] as List).join('\n• '),
            'weaknesses': (swotData['weaknesses'] as List).join('\n• '),
            'opportunities': (swotData['opportunities'] as List).join('\n• '),
            'threats': (swotData['threats'] as List).join('\n• '),
          };
        } catch (e) {
          // Fallback to text parsing
          return _parseSWOTFromText(content);
        }
      } else {
        throw Exception('Failed to generate SWOT analysis: ${response.statusCode}');
      }
    } catch (e) {
      throw Exception('Error generating SWOT analysis: $e');
    }
  }

  static Map<String, String> _parseSWOTFromText(String text) {
    final sections = <String, String>{};
    final lines = text.split('\n');
    String currentSection = '';
    StringBuffer currentContent = StringBuffer();

    for (String line in lines) {
      final lowerLine = line.toLowerCase();
      if (lowerLine.contains('strength')) {
        if (currentSection.isNotEmpty) {
          sections[currentSection] = currentContent.toString().trim();
        }
        currentSection = 'strengths';
        currentContent.clear();
      } else if (lowerLine.contains('weakness')) {
        if (currentSection.isNotEmpty) {
          sections[currentSection] = currentContent.toString().trim();
        }
        currentSection = 'weaknesses';
        currentContent.clear();
      } else if (lowerLine.contains('opportunit')) {
        if (currentSection.isNotEmpty) {
          sections[currentSection] = currentContent.toString().trim();
        }
        currentSection = 'opportunities';
        currentContent.clear();
      } else if (lowerLine.contains('threat')) {
        if (currentSection.isNotEmpty) {
          sections[currentSection] = currentContent.toString().trim();
        }
        currentSection = 'threats';
        currentContent.clear();
      } else if (currentSection.isNotEmpty && line.trim().isNotEmpty) {
        currentContent.writeln(line);
      }
    }

    if (currentSection.isNotEmpty) {
      sections[currentSection] = currentContent.toString().trim();
    }

    return sections;
  }

  static Future<String> generatePitchDeck({
    required String businessName,
    required String problemStatement,
    required String solution,
    required String marketSize,
    required String businessModel,
    required String teamInfo,
    required String financialProjections,
  }) async {
    try {
      final prompt = '''
Create a compelling pitch deck outline for:

Business Name: $businessName
Problem Statement: $problemStatement
Solution: $solution
Market Size: $marketSize
Business Model: $businessModel
Team: $teamInfo
Financial Projections: $financialProjections

Provide a detailed outline for each slide:
1. Title Slide
2. Problem
3. Solution
4. Market Opportunity
5. Product/Demo
6. Business Model
7. Traction
8. Competition
9. Team
10. Financial Projections
11. Funding Ask
12. Thank You/Contact

For each slide, provide specific content, key points, and presentation tips.
''';

      final response = await http.post(
        Uri.parse('$_baseUrl/chat/completions'),
        headers: {
          'Authorization': 'Bearer $_apiKey',
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://biznest.app',
          'X-Title': 'BizNest Pitch Deck Builder',
        },
        body: jsonEncode({
          'model': 'openai/gpt-3.5-turbo',
          'messages': [
            {
              'role': 'system',
              'content': 'You are an expert pitch deck consultant who has helped startups raise millions. Create compelling, investor-ready pitch deck content.'
            },
            {
              'role': 'user',
              'content': prompt,
            }
          ],
          'temperature': 0.7,
          'max_tokens': 3500,
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['choices'][0]['message']['content'];
      } else {
        throw Exception('Failed to generate pitch deck: ${response.statusCode}');
      }
    } catch (e) {
      throw Exception('Error generating pitch deck: $e');
    }
  }

  static Future<String> generateBusinessModelCanvas({
    required String businessName,
    required String industry,
    required String businessModel,
    required String targetMarket,
    required String competitors,
    required String description,
  }) async {
    try {
      final prompt = '''
Create a comprehensive Business Model Canvas for:

Business Name: $businessName
Industry: $industry
Business Model: $businessModel
Target Market: $targetMarket
Main Competitors: $competitors
Description: $description

Provide detailed content for each of the 9 Business Model Canvas building blocks:

1. **Key Partners**: Strategic alliances, key suppliers, key partners
2. **Key Activities**: Most important activities to make the business model work
3. **Key Resources**: Most important assets required to make the business model work
4. **Value Propositions**: The bundle of products and services that create value for customers
5. **Customer Relationships**: Types of relationships established with specific customer segments
6. **Channels**: How the company communicates and reaches its customer segments
7. **Customer Segments**: Different groups of people or organizations the business aims to reach
8. **Cost Structure**: Most important costs inherent in the business model
9. **Revenue Streams**: Cash generated from each customer segment

Format each section clearly with specific, actionable content relevant to the business.
''';

      final response = await http.post(
        Uri.parse('$_baseUrl/chat/completions'),
        headers: {
          'Authorization': 'Bearer $_apiKey',
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://biznest.app',
          'X-Title': 'BizNest Business Model Canvas Tool',
        },
        body: jsonEncode({
          'model': 'openai/gpt-3.5-turbo',
          'messages': [
            {
              'role': 'system',
              'content': 'You are a business strategy consultant expert in Business Model Canvas methodology. Create specific, actionable business model canvases.'
            },
            {
              'role': 'user',
              'content': prompt,
            }
          ],
          'temperature': 0.7,
          'max_tokens': 3500,
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        return data['choices'][0]['message']['content'];
      } else {
        throw Exception('Failed to generate Business Model Canvas: ${response.statusCode}');
      }
    } catch (e) {
      throw Exception('Error generating Business Model Canvas: $e');
    }
  }
}